version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Java 22
          command: |
            sudo apt-get update && sudo apt-get install -y wget
            wget https://download.java.net/java/GA/jdk22/830ec9fcccef480bb3e73fb7ecafe059/36/GPL/openjdk-22_linux-x64_bin.tar.gz
            sudo mkdir -p /usr/lib/jvm
            sudo tar zxvf openjdk-22_linux-x64_bin.tar.gz -C /usr/lib/jvm
            sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-22/bin/java 2200
            sudo update-alternatives --config java
            echo 'export PATH="/usr/lib/jvm/jdk-22/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
            java -version
      - run:
          name: Install Maven
          command: |
            sudo apt-get install -y maven
            mvn -version
      - run:
          name: Install Chrome
          command: |
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            google-chrome --version
    executor:

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build and Run Tests
          command: mvn clean test -Dsurefire.suiteXmlFiles=bvt.xml -Drun.headless=true -X
    executor:

  daily-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build and Run Tests
          command: mvn clean test -Dsurefire.suiteXmlFiles=bvt.xml -Drun.headless=true -X -Dcreate.cycle=true
    executor:

  nightly-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build and Run Tests
          command: mvn clean test -Dsurefire.suiteXmlFiles=regression.xml -Drun.headless=true
    executor:

workflows:
  version: 2
#  build-and-test:
#    jobs:
#      - build
#      - test:
#          requires:
#            - build

  scheduled-tests:
    triggers:
      - schedule:
          cron: "40 06 * * *"  # This will run nightly-test at 4:00 PM IST (10:30 AM UTC)
          filters:
            branches:
              only:
                - main
    jobs:
      - build
      - nightly-test:
          requires:
            - build
