version: 2.1

jobs:
  build-and-test:
    docker:
      - image: ubuntu:22.04  # Use a base Ubuntu image
    steps:
      - checkout
      - run:
          name: Install Java 22
          command: |
            apt-get update
            apt-get install -y wget
            wget https://download.java.net/java/GA/jdk22/latest/binaries/openjdk-22_linux-x64_bin.tar.gz
            tar -xvf openjdk-22_linux-x64_bin.tar.gz
            mv jdk-22 /opt/jdk-22
            export JAVA_HOME=/opt/jdk-22
            export PATH=$JAVA_HOME/bin:$PATH
      - run:
          name: Install Maven
          command: apt-get install -y maven
      - run:
          name: Verify Java Version
          command: java -version
      - run:
          name: Build and Run Tests
          command: mvn clean test -Dsurefire.suiteXmlFiles=smoke.xml -Drun.headless=true

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
