version: 2.1

executors:
  java-taurus-executor:
    docker:
      - image: cimg/openjdk:21.0
    working_directory: ~/repo
    resource_class: xlarge

jobs:
  taurus-selenium-ui-perf:
    executor: java-taurus-executor
    environment:
      USERS: 5
    steps:
      - checkout

      - run:
          name: Install Chrome 125 & matching ChromeDriver
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip curl gnupg fonts-liberation libasound2 libnss3 libxss1 libgconf-2-4 libappindicator1 libatk-bridge2.0-0 libgtk-3-0
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            # Install Chrome 125 specifically
            sudo apt-get install -y google-chrome-stable=125.0.6422.60-1
            CHROME_DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_125")
            wget "https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip"
            unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/local/bin/chromedriver
            sudo chmod +x /usr/local/bin/chromedriver
            chromedriver --version

      - run:
          name: Install Taurus
          command: |
            sudo apt-get install -y python3-pip
            pip3 install bzt

      - run:
          name: Build Project with Maven
          command: mvn clean package -e

      - run:
          name: Copy Dependencies
          command: mvn dependency:copy-dependencies -DoutputDirectory=target/dependency

      - run:
          name: Run Taurus UI Performance Test
          command: |
            mkdir -p results
            bzt taurus-config/selenium_order_flow.yml -o execution.0.concurrency=$USERS

      - store_artifacts:
          path: results

workflows:
  version: 2

  build-and-test:
    jobs:
      - taurus-selenium-ui-perf

  daily_manual_trigger:
    triggers:
      - schedule:
          cron: "28 16 * * 1-5"
          filters:
            branches:
              only:
                - order_flow_perf
    jobs:
      - taurus-selenium-ui-perf
#      - approve-before-run:
#          type: approval
#      - taurus-selenium-ui-perf:
#          requires:
#            - approve-before-run